# Generated by Django 3.2.7 on 2021-10-25 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageldapusers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ldapuser',
            old_name='isValide',
            new_name='isValid',
        ),
    ]
