# Generated by Django 3.2.7 on 2021-10-29 14:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageldapusers', '0006_ldapuser_token_validate_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapuser',
            name='token_reset_password',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
