# Generated by Django 3.2.7 on 2021-10-29 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('manageldapusers', '0007_ldapuser_token_reset_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldapuser',
            name='classname',
            field=models.CharField(choices=[('toto', 'tata'), ('LIM', 'LIMART'), ('ING', 'Ingesup'), ('ANIM', 'Animation'), ('ISEE', 'ISEE'), ('AUDIO', 'Audiovisuel')], max_length=255, null=True),
        ),
    ]
