# Generated by Django 3.2.8 on 2021-11-23 22:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('manageldapusers', '0009_auto_20211101_1826'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ldapuser',
            name='classname',
        ),
    ]
